/**
 * Common emojis for autocomplete
 * Format: shortcode -> emoji
 */
export const emojis: Record<string, string> = {
  // Smileys & Emotion
  smile: '😊',
  grin: '😀',
  joy: '😂',
  rofl: '🤣',
  wink: '😉',
  blush: '😊',
  heart_eyes: '😍',
  kiss: '😘',
  thinking: '🤔',
  neutral: '😐',
  expressionless: '😑',
  rolling_eyes: '🙄',
  hushed: '😯',
  flushed: '😳',
  disappointed: '😞',
  worried: '😟',
  angry: '😠',
  rage: '😡',
  cry: '😢',
  sob: '😭',
  scream: '😱',
  tired: '😫',
  sleepy: '😴',
  drool: '🤤',
  sunglasses: '😎',
  nerd: '🤓',
  confused: '😕',
  upside_down: '🙃',
  money_mouth: '🤑',
  astonished: '😲',
  sick: '🤢',
  sneezing: '🤧',
  mask: '😷',
  cowboy: '🤠',
  clown: '🤡',
  lying: '🤥',
  shush: '🤫',
  zipper_mouth: '🤐',
  raised_eyebrow: '🤨',
  monocle: '🧐',

  // Gestures & Body
  thumbsup: '👍',
  thumbsdown: '👎',
  ok: '👌',
  punch: '👊',
  fist: '✊',
  wave: '👋',
  raised_hand: '✋',
  palm: '🖐️',
  fingers_crossed: '🤞',
  victory: '✌️',
  love_you: '🤟',
  rock: '🤘',
  call: '🤙',
  point_up: '☝️',
  point_down: '👇',
  point_left: '👈',
  point_right: '👉',
  middle_finger: '🖕',
  clap: '👏',
  raised_hands: '🙌',
  open_hands: '👐',
  handshake: '🤝',
  pray: '🙏',
  writing_hand: '✍️',
  nail_polish: '💅',
  muscle: '💪',
  leg: '🦵',
  foot: '🦶',
  ear: '👂',
  nose: '👃',
  brain: '🧠',
  eyes: '👀',
  eye: '👁️',
  tongue: '👅',
  lips: '👄',

  // Hearts & Love
  heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  brown_heart: '🤎',
  broken_heart: '💔',
  heart_exclamation: '❣️',
  two_hearts: '💕',
  revolving_hearts: '💞',
  heartbeat: '💓',
  heartpulse: '💗',
  sparkling_heart: '💖',
  cupid: '💘',
  gift_heart: '💝',
  heart_decoration: '💟',

  // Objects & Symbols
  star: '⭐',
  star2: '🌟',
  sparkles: '✨',
  zap: '⚡',
  fire: '🔥',
  boom: '💥',
  100: '💯',
  money: '💰',
  dollar: '💵',
  gem: '💎',
  bulb: '💡',
  book: '📖',
  books: '📚',
  memo: '📝',
  pencil: '✏️',
  pen: '🖊️',
  paperclip: '📎',
  scissors: '✂️',
  file_folder: '📁',
  calendar: '📅',
  clock: '🕐',
  hourglass: '⏳',
  watch: '⌚',
  phone: '📱',
  computer: '💻',
  keyboard: '⌨️',
  email: '📧',
  package: '📦',
  gift: '🎁',
  balloon: '🎈',
  tada: '🎉',
  confetti: '🎊',
  trophy: '🏆',
  medal: '🏅',
  crown: '👑',
  ring: '💍',
  camera: '📷',
  video: '📹',
  tv: '📺',
  radio: '📻',
  microphone: '🎤',
  headphones: '🎧',
  musical_note: '🎵',
  notes: '🎶',
  guitar: '🎸',
  piano: '🎹',
  drum: '🥁',
  art: '🎨',
  palette: '🎨',
  movie: '🎬',
  ticket: '🎫',

  // Nature & Animals
  sun: '☀️',
  moon: '🌙',
  cloud: '☁️',
  rain: '🌧️',
  snow: '❄️',
  rainbow: '🌈',
  umbrella: '☂️',
  ocean: '🌊',
  tree: '🌳',
  flower: '🌸',
  rose: '🌹',
  tulip: '🌷',
  sunflower: '🌻',
  leaf: '🍃',
  fallen_leaf: '🍂',
  maple_leaf: '🍁',
  cactus: '🌵',
  palm_tree: '🌴',
  dog: '🐕',
  cat: '🐈',
  mouse: '🐁',
  rabbit: '🐇',
  fox: '🦊',
  bear: '🐻',
  panda: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐄',
  pig: '🐷',
  monkey: '🐵',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  eagle: '🦅',
  owl: '🦉',
  bat: '🦇',
  wolf: '🐺',
  horse: '🐴',
  unicorn: '🦄',
  bee: '🐝',
  butterfly: '🦋',
  snail: '🐌',
  bug: '🐛',
  ant: '🐜',
  spider: '🕷️',
  turtle: '🐢',
  snake: '🐍',
  lizard: '🦎',
  octopus: '🐙',
  fish: '🐟',
  dolphin: '🐬',
  whale: '🐳',
  shark: '🦈',
  crab: '🦀',

  // Food & Drink
  apple: '🍎',
  pear: '🍐',
  orange: '🍊',
  lemon: '🍋',
  banana: '🍌',
  watermelon: '🍉',
  grapes: '🍇',
  strawberry: '🍓',
  cherry: '🍒',
  peach: '🍑',
  mango: '🥭',
  pineapple: '🍍',
  coconut: '🥥',
  avocado: '🥑',
  tomato: '🍅',
  carrot: '🥕',
  corn: '🌽',
  pepper: '🌶️',
  broccoli: '🥦',
  pizza: '🍕',
  hamburger: '🍔',
  fries: '🍟',
  hotdog: '🌭',
  sandwich: '🥪',
  taco: '🌮',
  burrito: '🌯',
  egg: '🥚',
  cooking: '🍳',
  bread: '🍞',
  croissant: '🥐',
  cake: '🎂',
  cupcake: '🧁',
  pie: '🥧',
  cookie: '🍪',
  chocolate: '🍫',
  candy: '🍬',
  lollipop: '🍭',
  icecream: '🍨',
  donut: '🍩',
  coffee: '☕',
  tea: '🍵',
  beer: '🍺',
  wine: '🍷',
  cocktail: '🍸',
  champagne: '🍾',

  // Activities & Sports
  soccer: '⚽',
  basketball: '🏀',
  football: '🏈',
  baseball: '⚾',
  tennis: '🎾',
  volleyball: '🏐',
  rugby: '🏉',
  golf: '⛳',
  bowling: '🎳',
  hockey: '🏒',
  ping_pong: '🏓',
  badminton: '🏸',
  boxing: '🥊',
  martial_arts: '🥋',
  skiing: '⛷️',
  snowboard: '🏂',
  skateboard: '🛹',
  surfing: '🏄',
  swimming: '🏊',
  biking: '🚴',
  running: '🏃',
  walking: '🚶',
  yoga: '🧘',
  climbing: '🧗',

  // Travel & Places
  car: '🚗',
  taxi: '🚕',
  bus: '🚌',
  truck: '🚚',
  motorcycle: '🏍️',
  bicycle: '🚲',
  train: '🚆',
  metro: '🚇',
  plane: '✈️',
  helicopter: '🚁',
  rocket: '🚀',
  ship: '🚢',
  sailboat: '⛵',
  anchor: '⚓',
  fuel: '⛽',
  traffic_light: '🚦',
  construction: '🚧',
  house: '🏠',
  office: '🏢',
  hospital: '🏥',
  school: '🏫',
  hotel: '🏨',
  church: '⛪',
  mosque: '🕌',
  synagogue: '🕍',
  castle: '🏰',
  tent: '⛺',
  mountain: '⛰️',
  volcano: '🌋',
  desert: '🏜️',
  island: '🏝️',
  stadium: '🏟️',
  world: '🌍',
  globe: '🌎',
  map: '🗺️',
  compass: '🧭',

  // Arrows & Symbols
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrow_left: '⬅️',
  arrow_right: '➡️',
  arrow_upper_left: '↖️',
  arrow_upper_right: '↗️',
  arrow_lower_left: '↙️',
  arrow_lower_right: '↘️',
  left_right: '↔️',
  up_down: '↕️',
  arrows_clockwise: '🔃',
  arrows_counterclockwise: '🔄',
  back: '🔙',
  end: '🔚',
  top: '🔝',
  soon: '🔜',
  check: '✅',
  x: '❌',
  cross: '❎',
  plus: '➕',
  minus: '➖',
  divide: '➗',
  multiply: '✖️',
  question: '❓',
  exclamation: '❗',
  warning: '⚠️',
  no_entry: '⛔',
  prohibited: '🚫',
  stop: '🛑',

  // Flags (common ones)
  flag_white: '🏳️',
  flag_black: '🏴',
  checkered_flag: '🏁',
  rainbow_flag: '🏳️‍🌈',
  pirate_flag: '🏴‍☠️',
};

/**
 * Search emojis by shortcode
 */
export function searchEmojis(query: string, limit: number = 8): Array<{ code: string; emoji: string }> {
  if (!query) return [];

  const queryLower = query.toLowerCase();
  const results: Array<{ code: string; emoji: string; score: number }> = [];

  for (const [code, emoji] of Object.entries(emojis)) {
    if (code.startsWith(queryLower)) {
      results.push({ code, emoji, score: 100 - code.length });
    } else if (code.includes(queryLower)) {
      results.push({ code, emoji, score: 50 - code.indexOf(queryLower) });
    }
  }

  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(({ code, emoji }) => ({ code, emoji }));
}
