// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateNoteInput = { title: string | null, content: string | null, notebook_id: string | null, tags: Array<string> | null, };
