// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportStats = { notes: number, notebooks: number, tags: number, file_path: string, };
