// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportStats = { notes_imported: number, notebooks_imported: number, tags_imported: number, notes_skipped: number, notebooks_skipped: number, tags_skipped: number, };
