// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchOptions = { query: string, limit: bigint | null, offset: bigint | null, notebook_id: string | null, include_archived: boolean | null, include_trashed: boolean | null, };
