// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteStatus } from "./NoteStatus";

export type ListNotesFilter = { notebook_id: string | null, status: NoteStatus | null, tag: string | null, search: string | null, limit: bigint | null, offset: bigint | null, };
