// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalSyncState = { last_pull_revision: bigint, last_push_revision: bigint, last_synced_at: string | null, pending_changes: number, };
