// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteStatus } from "./NoteStatus";

export type Note = { id: string, title: string, content: string, notebook_id: string | null, tags: Array<string>, status: NoteStatus, is_pinned: boolean, revision: bigint, created_at: string, updated_at: string, deleted_at: string | null, };
