// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncConflict = { entity_type: string, entity_id: string, local_revision: bigint, remote_revision: bigint, resolution: string, };
