// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncConflict } from "./SyncConflict";
import type { SyncStats } from "./SyncStats";

export type SyncResult = { pulled: SyncStats, pushed: SyncStats, conflicts: Array<SyncConflict>, last_synced_at: string, };
