// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";
import type { Notebook } from "./Notebook";
import type { Tag } from "./Tag";

export type SyncPayload = { notes: Array<Note>, notebooks: Array<Notebook>, tags: Array<Tag>, since_revision: bigint, };
