// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tag = { id: string, name: string, color: string | null, revision: bigint, created_at: string, updated_at: string, deleted_at: string | null, };
