// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateNotebookInput = { name: string | null, color: string | null, icon: string | null, parent_id: string | null, };
