// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteStatus } from "./NoteStatus";

export type UpdateNoteInput = { title: string | null, content: string | null, notebook_id: string | null, tags: Array<string> | null, status: NoteStatus | null, is_pinned: boolean | null, };
